stages:
  - fit
    
fit_simple:
  stage: fit
  image: rootproject/root:6.22.06-conda
  script:
    - pwd
    - ls
    - echo $SERVICE_PASS | kinit $CERN_USER@CERN.CH
    - xrdcp root://eosuser.cern.ch//eos/user/m/meehan/APBootCampFeb20/Histograms/histograms.root histograms.root
    - mkdir fit_outputs
    - python fit.py histograms.root fit_outputs
  artifacts:
    paths:
    - fit_outputs
    expire_in: 1 week
    

    


